UPDATE A SET A.REM=B.REM FROM TF_POS A,TF_POS B,TF_SQ C
WHERE A.os_id='PO' AND A.qt_no like 'SQ%' AND (A.REM IS NULL or A.rem='') AND
B.os_id='SO' AND (B.REM IS NOT NULL AND B.rem != '') AND A.SQ_NO=C.SQ_NO AND
A.OTH_ITM=C.ITM AND C.SO_NO=B.OS_NO AND C.EST_ITM=B.ITM