
-- UPDATE A SET A.KHNBDH=C.KHNBDH FROM TF_POS_Z A,TF_POS B,TF_POS_Z C
-- WHERE A.OS_ID='PO' AND A.OS_NO=B.OS_NO AND B.OTH_NO=C.OS_NO
-- AND (A.KHNBDH IS NULL OR A.KHNBDH='') AND (C.KHNBDH IS NOT NULL OR C.KHNBDH != '')



 -- 012更新采购单表身客户内部单号 以下按次序2秒执行一次
UPDATE A SET A.KHNBDH=C.KHNBDH FROM TF_POS_Z A,TF_POS B,TF_POS_Z C,TF_POS D
WHERE A.OS_ID='PO' AND A.OS_NO=B.OS_NO AND B.OTH_NO=C.OS_NO AND
D.OS_ID='SO' AND C.OS_NO=D.OS_NO AND C.ITM=D.ITM AND B.OTH_ITM=C.ITM AND
(A.KHNBDH IS NULL OR A.KHNBDH='') AND (C.KHNBDH IS NOT NULL OR C.KHNBDH != '')