UPDATE A SET A.KHNBDH=C.KHNBDH FROM TF_POS_Z A,TF_POS B,TF_POS_Z C
WHERE A.OS_ID='PO' AND A.OS_NO=B.OS_NO AND B.OTH_NO=C.OS_NO
AND (A.KHNBDH IS NULL OR A.KHNBDH='') AND (C.KHNBDH IS NOT NULL OR C.KHNBDH != '')