UPDATE D SET D.SDDH=B.OS_NO FROM TF_POS A,TF_POS B,TF_SQ C,TF_POS_Z D
WHERE A.os_id='PO' AND A.qt_no like 'SQ%'  AND
B.os_id='SO'  AND A.SQ_NO=C.SQ_NO AND
A.OTH_ITM=C.ITM AND C.SO_NO=B.OS_NO AND C.EST_ITM=B.ITM AND
D.OS_NO=A.OS_NO AND (D.SDDH IS NULL OR D.SDDH='')